version: "3.7"

services:
  ml-app:
    container_name: ml-app
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=dev
      - FLASK_APP=app/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app

